ny_parking_violations_data:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../secrets/gcp_credentials.json
      location: "{{ env_var('GOOGLE_REGION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT') }}"
      threads: 3
      type: bigquery
  target: dev